services:
  user1:
    build: ./attacker
    container_name: user1
    networks:
      - rede-teste
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true

  user2:
    build: ./client
    container_name: user2
    networks:
      - rede-teste
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true

  monitor:
    build: .
    ports:
      - "8501:8501"
    container_name: monitor
    networks:
      - rede-teste
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true
    command: bash -c "source /opt/venv/bin/activate && streamlit run app.py"

networks:
  rede-teste:
    driver: macvlan
    driver_opts:
      parent: WiFi
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          gateway: "192.168.2.1"