services:
  server:
    build: ./server
    ports:
      - "8080:80"
    networks:
      - rede-teste
    hostname: server

  client-legit:
    build: ./client
    networks:
      - rede-teste
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:80
    hostname: client

  attacker:
    build: ./attacker
    networks:
      - rede-teste
    depends_on:
      - server
    environment:
      - TARGET_HOST=server
    hostname: attacker

  monitor:
    build: .
    ports:
      - "8501:8501"
      - "23:22"  # Adiciona porta SSH
    networks:
      - rede-teste
    volumes:
      - ./app:/app
    depends_on:
      - server
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    tty: true        # Adiciona terminal
    stdin_open: true # Permite interação
    command: bash -c "ip link set eth0 promisc on && streamlit run app.py"

networks:
  rede-teste:
    driver: bridge
    ipam: 
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
   
